import type { Prospect } from '~/types/prospect'

// NOTE: dummy data only — Prospek Saya has no backend endpoint yet, this is a UI prototype.
const dummyProspects: Prospect[] = [
  {
    id: 1,
    name: 'Rima Ayu Lestari',
    phone: '0812-3456-7890',
    address: 'Jakarta Selatan',
    services: ['Internet Home 100Mb'],
    estimatedPoints: 50,
    registDate: '2026-08-25',
    approvedDate: null,
    salesPic: 'Rendra Wijaya',
    notes: null,
    status: 'Diproses',
  },
  {
    id: 2,
    name: 'Bagas Wirawan',
    phone: '0813-2233-4455',
    address: 'Bekasi',
    services: ['Internet Home 100Mb', 'Nusawork Advance'],
    estimatedPoints: 125,
    registDate: '2026-08-24',
    approvedDate: null,
    salesPic: 'Rendra Wijaya',
    notes: null,
    status: 'Diproses',
  },
  {
    id: 3,
    name: 'Siti Nur Halimah',
    phone: '0857-9988-1122',
    address: 'Tangerang',
    services: ['Nusaselecta 100Mb'],
    estimatedPoints: 75,
    registDate: '2026-08-22',
    approvedDate: '2026-08-24',
    salesPic: 'Rendra Wijaya',
    notes: 'Data valid, lokasi terjangkau jaringan Nusaselecta.',
    status: 'Disetujui',
  },
  {
    id: 4,
    name: 'Dedi Kurniawan',
    phone: '0821-4567-8899',
    address: 'Depok',
    services: ['Nusawork Advance'],
    estimatedPoints: 120,
    registDate: '2026-08-20',
    approvedDate: '2026-08-21',
    salesPic: 'Hendra Saputra',
    notes: 'Sudah dikonfirmasi via telepon, siap dijadwalkan instalasi.',
    status: 'Disetujui',
  },
  {
    id: 5,
    name: 'Putri Ramadhani',
    phone: '0878-1122-3344',
    address: 'Bogor',
    services: ['Internet Home 100Mb', 'Nusaselecta 100Mb'],
    estimatedPoints: 170,
    registDate: '2026-08-19',
    approvedDate: '2026-08-20',
    salesPic: 'Rendra Wijaya',
    notes: 'Data lengkap dan sesuai.',
    status: 'Disetujui',
  },
  {
    id: 6,
    name: 'Andi Saputra',
    phone: '0856-7788-9900',
    address: 'Jakarta Timur',
    services: ['Internet Home 100Mb'],
    estimatedPoints: 50,
    registDate: '2026-08-18',
    approvedDate: null,
    salesPic: 'Hendra Saputra',
    notes: null,
    status: 'Diproses',
  },
  {
    id: 7,
    name: 'Maya Anggraini',
    phone: '0819-5566-7788',
    address: 'Jakarta Barat',
    services: ['Internet Home 100Mb', 'Nusawork Advance', 'Nusaselecta 100Mb'],
    estimatedPoints: 245,
    registDate: '2026-08-16',
    approvedDate: '2026-08-17',
    salesPic: 'Rendra Wijaya',
    notes: 'Pelanggan potensial, direkomendasikan untuk paket bundling.',
    status: 'Disetujui',
  },
  {
    id: 8,
    name: 'Fajar Ramadhan',
    phone: '0838-2211-0099',
    address: 'Tangerang Selatan',
    services: ['Nusawork Advance'],
    estimatedPoints: 120,
    registDate: '2026-08-14',
    approvedDate: '2026-08-15',
    salesPic: 'Hendra Saputra',
    notes: 'Data sudah diverifikasi lengkap.',
    status: 'Disetujui',
  },
]

export const useProspects = () => {
  const getProspects = (): Prospect[] => dummyProspects
  const getProspectById = (id: number): Prospect | null => dummyProspects.find(p => p.id === id) || null

  return { getProspects, getProspectById }
}
